# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '12'

            - run: yarn install

            # Linux build
            - run: yarn electron:build

            - uses: actions/upload-artifact@v2
              with:
                  name: Devtool Linux Appimage
                  path: dist_electron/devtool*.AppImage

            - uses: actions/upload-artifact@v2
              with:
                  name: Devtool Linux Snap
                  path: dist_electron/devtool*.snap

            - uses: actions/upload-artifact@v2
              with:
                  name: Devtool Linux Zip
                  path: dist_electron/linux-unpacked

            # Windows build
            - run: yarn electron:build --windows

            - uses: actions/upload-artifact@v2
              with:
                  name: Devtool Windows Installer
                  path: dist_electron/*Setup*.exe

            - uses: actions/upload-artifact@v2
              with:
                  name: Devtool Windows Zip
                  path: dist_electron/win-unpacked
